/**
  Generated Main Source File

  Company:
    Microchip Technology Inc.

  File Name:
    main.c

  Summary:
    This is the main file generated using PIC10 / PIC12 / PIC16 / PIC18 MCUs

  Description:
    This header file provides implementations for driver APIs for all modules selected in the GUI.
    Generation Information :
        Product Revision  :  PIC10 / PIC12 / PIC16 / PIC18 MCUs - 1.81.6
        Device            :  PIC16F19176
        Driver Version    :  2.00
*/

/*
    (c) 2018 Microchip Technology Inc. and its subsidiaries. 
    
    Subject to your compliance with these terms, you may use Microchip software and any 
    derivatives exclusively with Microchip products. It is your responsibility to comply with third party 
    license terms applicable to your use of third party software (including open source software) that 
    may accompany Microchip software.
    
    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER 
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY 
    IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS 
    FOR A PARTICULAR PURPOSE.
    
    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP 
    HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO 
    THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL 
    CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT 
    OF FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS 
    SOFTWARE.
*/

#include "mcc_generated_files/mcc.h"

/*
                         Main application
 */
void LCD_DIG0(unsigned char chr);
void LCD_DIG1(unsigned char chr);
void LCD_DIG2(unsigned char chr);
void LCD_DIG3(unsigned char chr);
void LCD_DIG4(unsigned char chr);
void LCD_DIG5(unsigned char chr);

void main(void)
{
    uint8_t count,c_count;
    // initialize the device
    SYSTEM_Initialize();

    // When using interrupts, you need to set the Global and Peripheral Interrupt Enable bits
    // Use the following macros to:

    // Enable the Global Interrupts
    INTERRUPT_GlobalInterruptEnable();

    // Enable the Peripheral Interrupts
    INTERRUPT_PeripheralInterruptEnable();

    // Disable the Global Interrupts
    //INTERRUPT_GlobalInterruptDisable();

    // Disable the Peripheral Interrupts
    //INTERRUPT_PeripheralInterruptDisable();

    count = 0;
    c_count = 'A';
    while (1)
    {
        // Add your application code
//        LCD_DIG_SYM00Num(0);
//        LCD_DIG_SYM01Num(1);
//        LCD_DIG_SYM02Num(2);
//        LCD_DIG_SYM03Num(3);
//        LCD_DIG_SYM04Num(4);
//        LCD_DIG_SYM05Num(5);
        
//        LCD_DisplayOn_DIG_SYM00Num();
//        LCD_DisplayOn_DIG_SYM01Num();
//        LCD_DisplayOn_DIG_SYM02Num();
//        LCD_DisplayOn_DIG_SYM03Num();
//        LCD_DisplayOn_DIG_SYM04Num();
//        LCD_DisplayOn_DIG_SYM05Num();
        
        LCD_DIG0(c_count);
        if(++c_count > 'Z') c_count = 'A';
        LCD_DIG1(c_count);
        if(++c_count > 'Z') c_count = 'A';
        LCD_DIG2(c_count);
        if(++c_count > 'Z') c_count = 'A';
        LCD_DIG3(c_count);
        if(++c_count > 'Z') c_count = 'A';
        LCD_DIG4(c_count);
        if(++c_count > 'Z') c_count = 'A';
        LCD_DIG5(c_count);
        if(++c_count > 'Z') c_count = 'A';
        
        //COL_SYM06ON;
        //COL_SYM07ON;
        //COL_SYM08ON;
        //COL_SYM09ON;
        
//        DOT_SYM11ON;
//        DOT_SYM12ON;
//        DOT_SYM13ON;
//        DOT_SYM14ON;
        
        BAR0_SYM10ON;
        BAR1_SYM15ON;
        BAR2_SYM16ON;
        //BAR3_SYM17ON;
        
        if(LCD_IsActive()){
            TEST_Toggle();
        }
        __delay_ms(2000);
        
        if(++count > 9) count = 0;
    }
}

void LCD_DIG0(unsigned char chr)
{
    switch (chr)
    {
        case 0: case '0': case 'O': DIG_SYM00AON;   DIG_SYM00BON;   DIG_SYM00CON;   DIG_SYM00DON;   DIG_SYM00EON;   DIG_SYM00FON;   DIG_SYM00GOFF;  break;
        case 1: case '1': DIG_SYM00AOFF;  DIG_SYM00BON;   DIG_SYM00CON;   DIG_SYM00DOFF;  DIG_SYM00EOFF;  DIG_SYM00FOFF;  DIG_SYM00GOFF;  break;
        case 2: case '2': DIG_SYM00AON;   DIG_SYM00BON;   DIG_SYM00COFF;  DIG_SYM00DON;   DIG_SYM00EON;   DIG_SYM00FOFF;  DIG_SYM00GON;   break;
        case 3: case '3': DIG_SYM00AON;   DIG_SYM00BON;   DIG_SYM00CON;   DIG_SYM00DON;   DIG_SYM00EOFF;  DIG_SYM00FOFF;  DIG_SYM00GON;   break;
        case 4: case '4': DIG_SYM00AOFF;  DIG_SYM00BON;   DIG_SYM00CON;   DIG_SYM00DOFF;  DIG_SYM00EOFF;  DIG_SYM00FON;   DIG_SYM00GON;   break;
        case 5: case '5': DIG_SYM00AON;   DIG_SYM00BOFF;  DIG_SYM00CON;   DIG_SYM00DON;   DIG_SYM00EOFF;  DIG_SYM00FON;   DIG_SYM00GON;   break;
        case 6: case '6': DIG_SYM00AON;   DIG_SYM00BOFF;  DIG_SYM00CON;   DIG_SYM00DON;   DIG_SYM00EON;   DIG_SYM00FON;   DIG_SYM00GON;   break;
        case 7: case '7': DIG_SYM00AON;   DIG_SYM00BON;   DIG_SYM00CON;   DIG_SYM00DOFF;  DIG_SYM00EOFF;  DIG_SYM00FOFF;  DIG_SYM00GOFF;  break;
        case 8: case '8': DIG_SYM00AON;   DIG_SYM00BON;   DIG_SYM00CON;   DIG_SYM00DON;   DIG_SYM00EON;   DIG_SYM00FON;   DIG_SYM00GON;   break;
        case 9: case '9': DIG_SYM00AON;   DIG_SYM00BON;   DIG_SYM00CON;   DIG_SYM00DON;   DIG_SYM00EOFF;  DIG_SYM00FON;   DIG_SYM00GON;   break;
        case 'A': case 'a': DIG_SYM00AON;   DIG_SYM00BON;   DIG_SYM00CON;   DIG_SYM00DOFF;   DIG_SYM00EON;   DIG_SYM00FON;   DIG_SYM00GON; break;
        case 'B': case 'b': DIG_SYM00AOFF; DIG_SYM00BOFF; DIG_SYM00CON; DIG_SYM00DON; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GON; break;
        case 'C': case 'c': DIG_SYM00AON; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DON; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GOFF; break;
        case 'D': case 'd': DIG_SYM00AOFF; DIG_SYM00BON; DIG_SYM00CON; DIG_SYM00DON; DIG_SYM00EON; DIG_SYM00FOFF; DIG_SYM00GON; break;
        case 'E': case 'e': DIG_SYM00AON; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DON; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GON; break;
        case 'F': case 'f': DIG_SYM00AON; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DOFF; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GON; break;
        case 'G': case 'g': DIG_SYM00AON; DIG_SYM00BOFF; DIG_SYM00CON; DIG_SYM00DON; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GOFF; break;
        case 'H': case 'h': DIG_SYM00AOFF; DIG_SYM00BON; DIG_SYM00CON; DIG_SYM00DOFF; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GON; break;
        case 'I': case 'i': DIG_SYM00AOFF; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DOFF; DIG_SYM00EOFF; DIG_SYM00FOFF; DIG_SYM00GOFF; break;
        case 'J': case 'j': DIG_SYM00AOFF; DIG_SYM00BON; DIG_SYM00CON; DIG_SYM00DON; DIG_SYM00EON; DIG_SYM00FOFF; DIG_SYM00GOFF; break;
        case 'K': case 'k': DIG_SYM00AOFF; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DOFF; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GON; break;
        case 'L': case 'l': DIG_SYM00AOFF; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DON; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GOFF; break;
        case 'M': case 'm': DIG_SYM00AOFF; DIG_SYM00BON; DIG_SYM00CON; DIG_SYM00DOFF; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GOFF; break;
        case 'N': case 'n': DIG_SYM00AOFF; DIG_SYM00BON; DIG_SYM00CON; DIG_SYM00DOFF; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GOFF; break;
        case 'o': DIG_SYM00AOFF; DIG_SYM00BOFF; DIG_SYM00CON; DIG_SYM00DON; DIG_SYM00EON; DIG_SYM00FOFF; DIG_SYM00GON; break;
        case 'P': case 'p': DIG_SYM00AON; DIG_SYM00BON; DIG_SYM00COFF; DIG_SYM00DOFF; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GON; break;
        case 'Q': case 'q': DIG_SYM00AON; DIG_SYM00BON; DIG_SYM00CON; DIG_SYM00DON; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GOFF; break;
        case 'R': case 'r': DIG_SYM00AON; DIG_SYM00BON; DIG_SYM00COFF; DIG_SYM00DOFF; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GON; break;
        case 'S': case 's': DIG_SYM00AON; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DON; DIG_SYM00EOFF; DIG_SYM00FOFF; DIG_SYM00GOFF; break;
        case 'T': case 't': DIG_SYM00AON; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DOFF; DIG_SYM00EOFF; DIG_SYM00FOFF; DIG_SYM00GOFF; break;
        case 'U': case 'u': DIG_SYM00AOFF; DIG_SYM00BON; DIG_SYM00CON; DIG_SYM00DON; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GOFF; break;
        case 'V': case 'v': DIG_SYM00AOFF; DIG_SYM00BON; DIG_SYM00CON; DIG_SYM00DOFF; DIG_SYM00EOFF; DIG_SYM00FOFF; DIG_SYM00GOFF; break;
        case 'W': case 'w': DIG_SYM00AOFF; DIG_SYM00BON; DIG_SYM00CON; DIG_SYM00DOFF; DIG_SYM00EON; DIG_SYM00FON; DIG_SYM00GOFF; break;
        case 'X': case 'x': DIG_SYM00AOFF; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DOFF; DIG_SYM00EOFF; DIG_SYM00FOFF; DIG_SYM00GOFF; break;
        case 'Y': case 'y': DIG_SYM00AOFF; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DOFF; DIG_SYM00EOFF; DIG_SYM00FOFF; DIG_SYM00GOFF; break;
        case 'Z': case 'z': DIG_SYM00AON; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DON; DIG_SYM00EOFF; DIG_SYM00FOFF; DIG_SYM00GOFF; break;
        
        
        default: DIG_SYM00AOFF; DIG_SYM00BOFF; DIG_SYM00COFF; DIG_SYM00DOFF; DIG_SYM00EOFF; DIG_SYM00FOFF; DIG_SYM00GOFF;
    }
    
    switch (chr)
    {
        case 0: case '0': case 'O': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF;  break;
        case 1: case '1': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF;  break;
        case 2: case '2': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF;  break;
        case 3: case '3': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF;  break;
        case 4: case '4': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF;  break;
        case 5: case '5': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF;  break;
        case 6: case '6': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF;  break;
        case 7: case '7': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF;  break;
        case 8: case '8': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF;  break;
        case 9: case '9': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF;  break;
        case 'A': case 'a': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'B': case 'b': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'C': case 'c': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'D': case 'd': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'E': case 'e': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'F': case 'f': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'G': case 'g': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'H': case 'h': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'I': case 'i': CHAR_SYM18AOFF; CHAR_SYM18BON; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FON; CHAR_SYM18GOFF; break;
        case 'J': case 'j': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'K': case 'k': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18CON; CHAR_SYM18DOFF; CHAR_SYM18EON; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'L': case 'l': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'M': case 'm': CHAR_SYM18AON; CHAR_SYM18BOFF; CHAR_SYM18CON; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'N': case 'n': CHAR_SYM18AON; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EON; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'o': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'P': case 'p': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'Q': case 'q': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EON; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'R': case 'r': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DON; CHAR_SYM18EON; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'S': case 's': CHAR_SYM18AON; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EON; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'T': case 't': CHAR_SYM18AOFF; CHAR_SYM18BON; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FON; CHAR_SYM18GOFF; break;
        case 'U': case 'u': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'V': case 'v': CHAR_SYM18AON; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EON; CHAR_SYM18FOFF; CHAR_SYM18GOFF; break;
        case 'W': case 'w': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EON; CHAR_SYM18FOFF; CHAR_SYM18GON; break;
        case 'X': case 'x': CHAR_SYM18AON; CHAR_SYM18BOFF; CHAR_SYM18CON; CHAR_SYM18DOFF; CHAR_SYM18EON; CHAR_SYM18FOFF; CHAR_SYM18GON; break;
        case 'Y': case 'y': CHAR_SYM18AON; CHAR_SYM18BOFF; CHAR_SYM18CON; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FON; CHAR_SYM18GOFF; break;
        case 'Z': case 'z': CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18CON; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GON; break;
        
        
        default: CHAR_SYM18AOFF; CHAR_SYM18BOFF; CHAR_SYM18COFF; CHAR_SYM18DOFF; CHAR_SYM18EOFF; CHAR_SYM18FOFF; CHAR_SYM18GOFF;
    }
}

void LCD_DIG1(unsigned char chr)
{
    switch (chr)
    {
        case 0: case '0': case 'O':DIG_SYM01AON;   DIG_SYM01BON;   DIG_SYM01CON;   DIG_SYM01DON;   DIG_SYM01EON;   DIG_SYM01FON;   DIG_SYM01GOFF;  break;
        case 1: case '1': DIG_SYM01AOFF;  DIG_SYM01BON;   DIG_SYM01CON;   DIG_SYM01DOFF;  DIG_SYM01EOFF;  DIG_SYM01FOFF;  DIG_SYM01GOFF;  break;
        case 2: case '2': DIG_SYM01AON;   DIG_SYM01BON;   DIG_SYM01COFF;  DIG_SYM01DON;   DIG_SYM01EON;   DIG_SYM01FOFF;  DIG_SYM01GON;   break;
        case 3: case '3': DIG_SYM01AON;   DIG_SYM01BON;   DIG_SYM01CON;   DIG_SYM01DON;   DIG_SYM01EOFF;  DIG_SYM01FOFF;  DIG_SYM01GON;   break;
        case 4: case '4': DIG_SYM01AOFF;  DIG_SYM01BON;   DIG_SYM01CON;   DIG_SYM01DOFF;  DIG_SYM01EOFF;  DIG_SYM01FON;   DIG_SYM01GON;   break;
        case 5: case '5': DIG_SYM01AON;   DIG_SYM01BOFF;  DIG_SYM01CON;   DIG_SYM01DON;   DIG_SYM01EOFF;  DIG_SYM01FON;   DIG_SYM01GON;   break;
        case 6: case '6': DIG_SYM01AON;   DIG_SYM01BOFF;  DIG_SYM01CON;   DIG_SYM01DON;   DIG_SYM01EON;   DIG_SYM01FON;   DIG_SYM01GON;   break;
        case 7: case '7': DIG_SYM01AON;   DIG_SYM01BON;   DIG_SYM01CON;   DIG_SYM01DOFF;  DIG_SYM01EOFF;  DIG_SYM01FOFF;  DIG_SYM01GOFF;  break;
        case 8: case '8': DIG_SYM01AON;   DIG_SYM01BON;   DIG_SYM01CON;   DIG_SYM01DON;   DIG_SYM01EON;   DIG_SYM01FON;   DIG_SYM01GON;   break;
        case 9: case '9': DIG_SYM01AON;   DIG_SYM01BON;   DIG_SYM01CON;   DIG_SYM01DON;   DIG_SYM01EOFF;  DIG_SYM01FON;   DIG_SYM01GON;   break;
        case 'A': case 'a': DIG_SYM01AON;   DIG_SYM01BON;   DIG_SYM01CON;   DIG_SYM01DOFF;   DIG_SYM01EON;   DIG_SYM01FON;   DIG_SYM01GON; break;
        case 'B': case 'b': DIG_SYM01AOFF; DIG_SYM01BOFF; DIG_SYM01CON; DIG_SYM01DON; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GON; break;
        case 'C': case 'c': DIG_SYM01AON; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DON; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GOFF; break;
        case 'D': case 'd': DIG_SYM01AOFF; DIG_SYM01BON; DIG_SYM01CON; DIG_SYM01DON; DIG_SYM01EON; DIG_SYM01FOFF; DIG_SYM01GON; break;
        case 'E': case 'e': DIG_SYM01AON; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DON; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GON; break;
        case 'F': case 'f': DIG_SYM01AON; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DOFF; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GON; break;
        case 'G': case 'g': DIG_SYM01AON; DIG_SYM01BOFF; DIG_SYM01CON; DIG_SYM01DON; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GOFF; break;
        case 'H': case 'h': DIG_SYM01AOFF; DIG_SYM01BON; DIG_SYM01CON; DIG_SYM01DOFF; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GON; break;
        case 'I': case 'i': DIG_SYM01AOFF; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DOFF; DIG_SYM01EOFF; DIG_SYM01FOFF; DIG_SYM01GOFF; break;
        case 'J': case 'j': DIG_SYM01AOFF; DIG_SYM01BON; DIG_SYM01CON; DIG_SYM01DON; DIG_SYM01EON; DIG_SYM01FOFF; DIG_SYM01GOFF; break;
        case 'K': case 'k': DIG_SYM01AOFF; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DOFF; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GON; break;
        case 'L': case 'l': DIG_SYM01AOFF; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DON; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GOFF; break;
        case 'M': case 'm': DIG_SYM01AOFF; DIG_SYM01BON; DIG_SYM01CON; DIG_SYM01DOFF; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GOFF; break;
        case 'N': case 'n': DIG_SYM01AOFF; DIG_SYM01BON; DIG_SYM01CON; DIG_SYM01DOFF; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GOFF; break;
        case 'o': DIG_SYM01AOFF; DIG_SYM01BOFF; DIG_SYM01CON; DIG_SYM01DON; DIG_SYM01EON; DIG_SYM01FOFF; DIG_SYM01GON; break;
        case 'P': case 'p': DIG_SYM01AON; DIG_SYM01BON; DIG_SYM01COFF; DIG_SYM01DOFF; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GON; break;
        case 'Q': case 'q': DIG_SYM01AON; DIG_SYM01BON; DIG_SYM01CON; DIG_SYM01DON; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GOFF; break;
        case 'R': case 'r': DIG_SYM01AON; DIG_SYM01BON; DIG_SYM01COFF; DIG_SYM01DOFF; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GON; break;
        case 'S': case 's': DIG_SYM01AON; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DON; DIG_SYM01EOFF; DIG_SYM01FOFF; DIG_SYM01GOFF; break;
        case 'T': case 't': DIG_SYM01AON; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DOFF; DIG_SYM01EOFF; DIG_SYM01FOFF; DIG_SYM01GOFF; break;
        case 'U': case 'u': DIG_SYM01AOFF; DIG_SYM01BON; DIG_SYM01CON; DIG_SYM01DON; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GOFF; break;
        case 'V': case 'v': DIG_SYM01AOFF; DIG_SYM01BON; DIG_SYM01CON; DIG_SYM01DOFF; DIG_SYM01EOFF; DIG_SYM01FOFF; DIG_SYM01GOFF; break;
        case 'W': case 'w': DIG_SYM01AOFF; DIG_SYM01BON; DIG_SYM01CON; DIG_SYM01DOFF; DIG_SYM01EON; DIG_SYM01FON; DIG_SYM01GOFF; break;
        case 'X': case 'x': DIG_SYM01AOFF; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DOFF; DIG_SYM01EOFF; DIG_SYM01FOFF; DIG_SYM01GOFF; break;
        case 'Y': case 'y': DIG_SYM01AOFF; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DOFF; DIG_SYM01EOFF; DIG_SYM01FOFF; DIG_SYM01GOFF; break;
        case 'Z': case 'z': DIG_SYM01AON; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DON; DIG_SYM01EOFF; DIG_SYM01FOFF; DIG_SYM01GOFF; break;

        default: DIG_SYM01AOFF; DIG_SYM01BOFF; DIG_SYM01COFF; DIG_SYM01DOFF; DIG_SYM01EOFF; DIG_SYM01FOFF; DIG_SYM01GOFF;
    }    
    
    switch (chr)
    {
        case 0: case '0': case 'O': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF;  break;
        case 1: case '1': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF;  break;
        case 2: case '2': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF;  break;
        case 3: case '3': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF;  break;
        case 4: case '4': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF;  break;
        case 5: case '5': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF;  break;
        case 6: case '6': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF;  break;
        case 7: case '7': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF;  break;
        case 8: case '8': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF;  break;
        case 9: case '9': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF;  break;
        case 'A': case 'a': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'B': case 'b': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'C': case 'c': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'D': case 'd': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'E': case 'e': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'F': case 'f': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'G': case 'g': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'H': case 'h': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'I': case 'i': CHAR_SYM19AOFF; CHAR_SYM19BON; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FON; CHAR_SYM19GOFF; break;
        case 'J': case 'j': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'K': case 'k': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19CON; CHAR_SYM19DOFF; CHAR_SYM19EON; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'L': case 'l': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'M': case 'm': CHAR_SYM19AON; CHAR_SYM19BOFF; CHAR_SYM19CON; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'N': case 'n': CHAR_SYM19AON; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EON; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'o': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'P': case 'p': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'Q': case 'q': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EON; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'R': case 'r': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DON; CHAR_SYM19EON; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'S': case 's': CHAR_SYM19AON; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EON; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'T': case 't': CHAR_SYM19AOFF; CHAR_SYM19BON; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FON; CHAR_SYM19GOFF; break;
        case 'U': case 'u': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'V': case 'v': CHAR_SYM19AON; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EON; CHAR_SYM19FOFF; CHAR_SYM19GOFF; break;
        case 'W': case 'w': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EON; CHAR_SYM19FOFF; CHAR_SYM19GON; break;
        case 'X': case 'x': CHAR_SYM19AON; CHAR_SYM19BOFF; CHAR_SYM19CON; CHAR_SYM19DOFF; CHAR_SYM19EON; CHAR_SYM19FOFF; CHAR_SYM19GON; break;
        case 'Y': case 'y': CHAR_SYM19AON; CHAR_SYM19BOFF; CHAR_SYM19CON; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FON; CHAR_SYM19GOFF; break;
        case 'Z': case 'z': CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19CON; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GON; break;

        default: CHAR_SYM19AOFF; CHAR_SYM19BOFF; CHAR_SYM19COFF; CHAR_SYM19DOFF; CHAR_SYM19EOFF; CHAR_SYM19FOFF; CHAR_SYM19GOFF;
    }  
}

void LCD_DIG2(unsigned char chr) 
{
    switch (chr)
    {
        case 0: case '0': case 'O': DIG_SYM02AON;   DIG_SYM02BON;   DIG_SYM02CON;   DIG_SYM02DON;   DIG_SYM02EON;   DIG_SYM02FON;   DIG_SYM02GOFF;  break;
        case 1: case '1': DIG_SYM02AOFF;  DIG_SYM02BON;   DIG_SYM02CON;   DIG_SYM02DOFF;  DIG_SYM02EOFF;  DIG_SYM02FOFF;  DIG_SYM02GOFF;  break;
        case 2: case '2': DIG_SYM02AON;   DIG_SYM02BON;   DIG_SYM02COFF;  DIG_SYM02DON;   DIG_SYM02EON;   DIG_SYM02FOFF;  DIG_SYM02GON;   break;
        case 3: case '3': DIG_SYM02AON;   DIG_SYM02BON;   DIG_SYM02CON;   DIG_SYM02DON;   DIG_SYM02EOFF;  DIG_SYM02FOFF;  DIG_SYM02GON;   break;
        case 4: case '4': DIG_SYM02AOFF;  DIG_SYM02BON;   DIG_SYM02CON;   DIG_SYM02DOFF;  DIG_SYM02EOFF;  DIG_SYM02FON;   DIG_SYM02GON;   break;
        case 5: case '5': DIG_SYM02AON;   DIG_SYM02BOFF;  DIG_SYM02CON;   DIG_SYM02DON;   DIG_SYM02EOFF;  DIG_SYM02FON;   DIG_SYM02GON;   break;
        case 6: case '6': DIG_SYM02AON;   DIG_SYM02BOFF;  DIG_SYM02CON;   DIG_SYM02DON;   DIG_SYM02EON;   DIG_SYM02FON;   DIG_SYM02GON;   break;
        case 7: case '7': DIG_SYM02AON;   DIG_SYM02BON;   DIG_SYM02CON;   DIG_SYM02DOFF;  DIG_SYM02EOFF;  DIG_SYM02FOFF;  DIG_SYM02GOFF;  break;
        case 8: case '8': DIG_SYM02AON;   DIG_SYM02BON;   DIG_SYM02CON;   DIG_SYM02DON;   DIG_SYM02EON;   DIG_SYM02FON;   DIG_SYM02GON;   break;
        case 9: case '9': DIG_SYM02AON;   DIG_SYM02BON;   DIG_SYM02CON;   DIG_SYM02DON;   DIG_SYM02EOFF;  DIG_SYM02FON;   DIG_SYM02GON;   break;
        case 'A': case 'a': DIG_SYM02AON;   DIG_SYM02BON;   DIG_SYM02CON;   DIG_SYM02DOFF;   DIG_SYM02EON;   DIG_SYM02FON;   DIG_SYM02GON; break;
        case 'B': case 'b': DIG_SYM02AOFF; DIG_SYM02BOFF; DIG_SYM02CON; DIG_SYM02DON; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GON; break;
        case 'C': case 'c': DIG_SYM02AON; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DON; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GOFF; break;
        case 'D': case 'd': DIG_SYM02AOFF; DIG_SYM02BON; DIG_SYM02CON; DIG_SYM02DON; DIG_SYM02EON; DIG_SYM02FOFF; DIG_SYM02GON; break;
        case 'E': case 'e': DIG_SYM02AON; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DON; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GON; break;
        case 'F': case 'f': DIG_SYM02AON; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DOFF; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GON; break;
        case 'G': case 'g': DIG_SYM02AON; DIG_SYM02BOFF; DIG_SYM02CON; DIG_SYM02DON; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GOFF; break;
        case 'H': case 'h': DIG_SYM02AOFF; DIG_SYM02BON; DIG_SYM02CON; DIG_SYM02DOFF; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GON; break;
        case 'I': case 'i': DIG_SYM02AOFF; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DOFF; DIG_SYM02EOFF; DIG_SYM02FOFF; DIG_SYM02GOFF; break;
        case 'J': case 'j': DIG_SYM02AOFF; DIG_SYM02BON; DIG_SYM02CON; DIG_SYM02DON; DIG_SYM02EON; DIG_SYM02FOFF; DIG_SYM02GOFF; break;
        case 'K': case 'k': DIG_SYM02AOFF; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DOFF; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GON; break;
        case 'L': case 'l': DIG_SYM02AOFF; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DON; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GOFF; break;
        case 'M': case 'm': DIG_SYM02AOFF; DIG_SYM02BON; DIG_SYM02CON; DIG_SYM02DOFF; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GOFF; break;
        case 'N': case 'n': DIG_SYM02AOFF; DIG_SYM02BON; DIG_SYM02CON; DIG_SYM02DOFF; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GOFF; break;
        case 'o': DIG_SYM02AOFF; DIG_SYM02BOFF; DIG_SYM02CON; DIG_SYM02DON; DIG_SYM02EON; DIG_SYM02FOFF; DIG_SYM02GON; break;
        case 'P': case 'p': DIG_SYM02AON; DIG_SYM02BON; DIG_SYM02COFF; DIG_SYM02DOFF; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GON; break;
        case 'Q': case 'q': DIG_SYM02AON; DIG_SYM02BON; DIG_SYM02CON; DIG_SYM02DON; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GOFF; break;
        case 'R': case 'r': DIG_SYM02AON; DIG_SYM02BON; DIG_SYM02COFF; DIG_SYM02DOFF; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GON; break;
        case 'S': case 's': DIG_SYM02AON; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DON; DIG_SYM02EOFF; DIG_SYM02FOFF; DIG_SYM02GOFF; break;
        case 'T': case 't': DIG_SYM02AON; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DOFF; DIG_SYM02EOFF; DIG_SYM02FOFF; DIG_SYM02GOFF; break;
        case 'U': case 'u': DIG_SYM02AOFF; DIG_SYM02BON; DIG_SYM02CON; DIG_SYM02DON; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GOFF; break;
        case 'V': case 'v': DIG_SYM02AOFF; DIG_SYM02BON; DIG_SYM02CON; DIG_SYM02DOFF; DIG_SYM02EOFF; DIG_SYM02FOFF; DIG_SYM02GOFF; break;
        case 'W': case 'w': DIG_SYM02AOFF; DIG_SYM02BON; DIG_SYM02CON; DIG_SYM02DOFF; DIG_SYM02EON; DIG_SYM02FON; DIG_SYM02GOFF; break;
        case 'X': case 'x': DIG_SYM02AOFF; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DOFF; DIG_SYM02EOFF; DIG_SYM02FOFF; DIG_SYM02GOFF; break;
        case 'Y': case 'y': DIG_SYM02AOFF; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DOFF; DIG_SYM02EOFF; DIG_SYM02FOFF; DIG_SYM02GOFF; break;
        case 'Z': case 'z': DIG_SYM02AON; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DON; DIG_SYM02EOFF; DIG_SYM02FOFF; DIG_SYM02GOFF; break;

        default: DIG_SYM02AOFF; DIG_SYM02BOFF; DIG_SYM02COFF; DIG_SYM02DOFF; DIG_SYM02EOFF; DIG_SYM02FOFF; DIG_SYM02GOFF;
    }    
    
    switch (chr)
    {
        case 0: case '0': case 'O': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF;  break;
        case 1: case '1': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF;  break;
        case 2: case '2': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF;  break;
        case 3: case '3': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF;  break;
        case 4: case '4': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF;  break;
        case 5: case '5': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF;  break;
        case 6: case '6': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF;  break;
        case 7: case '7': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF;  break;
        case 8: case '8': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF;  break;
        case 9: case '9': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF;  break;
        case 'A': case 'a': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'B': case 'b': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'C': case 'c': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'D': case 'd': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'E': case 'e': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'F': case 'f': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'G': case 'g': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'H': case 'h': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'I': case 'i': CHAR_SYM20AOFF; CHAR_SYM20BON; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FON; CHAR_SYM20GOFF; break;
        case 'J': case 'j': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'K': case 'k': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20CON; CHAR_SYM20DOFF; CHAR_SYM20EON; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'L': case 'l': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'M': case 'm': CHAR_SYM20AON; CHAR_SYM20BOFF; CHAR_SYM20CON; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'N': case 'n': CHAR_SYM20AON; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EON; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'o': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'P': case 'p': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'Q': case 'q': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EON; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'R': case 'r': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DON; CHAR_SYM20EON; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'S': case 's': CHAR_SYM20AON; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EON; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'T': case 't': CHAR_SYM20AOFF; CHAR_SYM20BON; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FON; CHAR_SYM20GOFF; break;
        case 'U': case 'u': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'V': case 'v': CHAR_SYM20AON; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EON; CHAR_SYM20FOFF; CHAR_SYM20GOFF; break;
        case 'W': case 'w': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EON; CHAR_SYM20FOFF; CHAR_SYM20GON; break;
        case 'X': case 'x': CHAR_SYM20AON; CHAR_SYM20BOFF; CHAR_SYM20CON; CHAR_SYM20DOFF; CHAR_SYM20EON; CHAR_SYM20FOFF; CHAR_SYM20GON; break;
        case 'Y': case 'y': CHAR_SYM20AON; CHAR_SYM20BOFF; CHAR_SYM20CON; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FON; CHAR_SYM20GOFF; break;
        case 'Z': case 'z': CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20CON; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GON; break;

        default: CHAR_SYM20AOFF; CHAR_SYM20BOFF; CHAR_SYM20COFF; CHAR_SYM20DOFF; CHAR_SYM20EOFF; CHAR_SYM20FOFF; CHAR_SYM20GOFF;
    }
}

void LCD_DIG3(unsigned char chr)
{
    switch (chr)
    {
        case 0: case '0': case 'O': DIG_SYM03AON;   DIG_SYM03BON;   DIG_SYM03CON;   DIG_SYM03DON;   DIG_SYM03EON;   DIG_SYM03FON;   DIG_SYM03GOFF;  break;
        case 1: case '1': DIG_SYM03AOFF;  DIG_SYM03BON;   DIG_SYM03CON;   DIG_SYM03DOFF;  DIG_SYM03EOFF;  DIG_SYM03FOFF;  DIG_SYM03GOFF;  break;
        case 2: case '2': DIG_SYM03AON;   DIG_SYM03BON;   DIG_SYM03COFF;  DIG_SYM03DON;   DIG_SYM03EON;   DIG_SYM03FOFF;  DIG_SYM03GON;   break;
        case 3: case '3': DIG_SYM03AON;   DIG_SYM03BON;   DIG_SYM03CON;   DIG_SYM03DON;   DIG_SYM03EOFF;  DIG_SYM03FOFF;  DIG_SYM03GON;   break;
        case 4: case '4': DIG_SYM03AOFF;  DIG_SYM03BON;   DIG_SYM03CON;   DIG_SYM03DOFF;  DIG_SYM03EOFF;  DIG_SYM03FON;   DIG_SYM03GON;   break;
        case 5: case '5': DIG_SYM03AON;   DIG_SYM03BOFF;  DIG_SYM03CON;   DIG_SYM03DON;   DIG_SYM03EOFF;  DIG_SYM03FON;   DIG_SYM03GON;   break;
        case 6: case '6': DIG_SYM03AON;   DIG_SYM03BOFF;  DIG_SYM03CON;   DIG_SYM03DON;   DIG_SYM03EON;   DIG_SYM03FON;   DIG_SYM03GON;   break;
        case 7: case '7': DIG_SYM03AON;   DIG_SYM03BON;   DIG_SYM03CON;   DIG_SYM03DOFF;  DIG_SYM03EOFF;  DIG_SYM03FOFF;  DIG_SYM03GOFF;  break;
        case 8: case '8': DIG_SYM03AON;   DIG_SYM03BON;   DIG_SYM03CON;   DIG_SYM03DON;   DIG_SYM03EON;   DIG_SYM03FON;   DIG_SYM03GON;   break;
        case 9: case '9': DIG_SYM03AON;   DIG_SYM03BON;   DIG_SYM03CON;   DIG_SYM03DON;   DIG_SYM03EOFF;  DIG_SYM03FON;   DIG_SYM03GON;   break;
        case 'A': case 'a': DIG_SYM03AON;   DIG_SYM03BON;   DIG_SYM03CON;   DIG_SYM03DOFF;   DIG_SYM03EON;   DIG_SYM03FON;   DIG_SYM03GON; break;
        case 'B': case 'b': DIG_SYM03AOFF; DIG_SYM03BOFF; DIG_SYM03CON; DIG_SYM03DON; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GON; break;
        case 'C': case 'c': DIG_SYM03AON; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DON; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GOFF; break;
        case 'D': case 'd': DIG_SYM03AOFF; DIG_SYM03BON; DIG_SYM03CON; DIG_SYM03DON; DIG_SYM03EON; DIG_SYM03FOFF; DIG_SYM03GON; break;
        case 'E': case 'e': DIG_SYM03AON; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DON; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GON; break;
        case 'F': case 'f': DIG_SYM03AON; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DOFF; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GON; break;
        case 'G': case 'g': DIG_SYM03AON; DIG_SYM03BOFF; DIG_SYM03CON; DIG_SYM03DON; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GOFF; break;
        case 'H': case 'h': DIG_SYM03AOFF; DIG_SYM03BON; DIG_SYM03CON; DIG_SYM03DOFF; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GON; break;
        case 'I': case 'i': DIG_SYM03AOFF; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DOFF; DIG_SYM03EOFF; DIG_SYM03FOFF; DIG_SYM03GOFF; break;
        case 'J': case 'j': DIG_SYM03AOFF; DIG_SYM03BON; DIG_SYM03CON; DIG_SYM03DON; DIG_SYM03EON; DIG_SYM03FOFF; DIG_SYM03GOFF; break;
        case 'K': case 'k': DIG_SYM03AOFF; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DOFF; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GON; break;
        case 'L': case 'l': DIG_SYM03AOFF; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DON; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GOFF; break;
        case 'M': case 'm': DIG_SYM03AOFF; DIG_SYM03BON; DIG_SYM03CON; DIG_SYM03DOFF; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GOFF; break;
        case 'N': case 'n': DIG_SYM03AOFF; DIG_SYM03BON; DIG_SYM03CON; DIG_SYM03DOFF; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GOFF; break;
        case 'o': DIG_SYM03AOFF; DIG_SYM03BOFF; DIG_SYM03CON; DIG_SYM03DON; DIG_SYM03EON; DIG_SYM03FOFF; DIG_SYM03GON; break;
        case 'P': case 'p': DIG_SYM03AON; DIG_SYM03BON; DIG_SYM03COFF; DIG_SYM03DOFF; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GON; break;
        case 'Q': case 'q': DIG_SYM03AON; DIG_SYM03BON; DIG_SYM03CON; DIG_SYM03DON; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GOFF; break;
        case 'R': case 'r': DIG_SYM03AON; DIG_SYM03BON; DIG_SYM03COFF; DIG_SYM03DOFF; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GON; break;
        case 'S': case 's': DIG_SYM03AON; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DON; DIG_SYM03EOFF; DIG_SYM03FOFF; DIG_SYM03GOFF; break;
        case 'T': case 't': DIG_SYM03AON; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DOFF; DIG_SYM03EOFF; DIG_SYM03FOFF; DIG_SYM03GOFF; break;
        case 'U': case 'u': DIG_SYM03AOFF; DIG_SYM03BON; DIG_SYM03CON; DIG_SYM03DON; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GOFF; break;
        case 'V': case 'v': DIG_SYM03AOFF; DIG_SYM03BON; DIG_SYM03CON; DIG_SYM03DOFF; DIG_SYM03EOFF; DIG_SYM03FOFF; DIG_SYM03GOFF; break;
        case 'W': case 'w': DIG_SYM03AOFF; DIG_SYM03BON; DIG_SYM03CON; DIG_SYM03DOFF; DIG_SYM03EON; DIG_SYM03FON; DIG_SYM03GOFF; break;
        case 'X': case 'x': DIG_SYM03AOFF; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DOFF; DIG_SYM03EOFF; DIG_SYM03FOFF; DIG_SYM03GOFF; break;
        case 'Y': case 'y': DIG_SYM03AOFF; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DOFF; DIG_SYM03EOFF; DIG_SYM03FOFF; DIG_SYM03GOFF; break;
        case 'Z': case 'z': DIG_SYM03AON; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DON; DIG_SYM03EOFF; DIG_SYM03FOFF; DIG_SYM03GOFF; break;

        default: DIG_SYM03AOFF; DIG_SYM03BOFF; DIG_SYM03COFF; DIG_SYM03DOFF; DIG_SYM03EOFF; DIG_SYM03FOFF; DIG_SYM03GOFF;
    }    
    
    switch (chr)
    {
        case 0: case '0': case 'O': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF;  break;
        case 1: case '1': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF;  break;
        case 2: case '2': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF;  break;
        case 3: case '3': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF;  break;
        case 4: case '4': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF;  break;
        case 5: case '5': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF;  break;
        case 6: case '6': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF;  break;
        case 7: case '7': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF;  break;
        case 8: case '8': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF;  break;
        case 9: case '9': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF;  break;
        case 'A': case 'a': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'B': case 'b': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'C': case 'c': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'D': case 'd': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'E': case 'e': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'F': case 'f': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'G': case 'g': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'H': case 'h': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'I': case 'i': CHAR_SYM21AOFF; CHAR_SYM21BON; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FON; CHAR_SYM21GOFF; break;
        case 'J': case 'j': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'K': case 'k': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21CON; CHAR_SYM21DOFF; CHAR_SYM21EON; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'L': case 'l': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'M': case 'm': CHAR_SYM21AON; CHAR_SYM21BOFF; CHAR_SYM21CON; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'N': case 'n': CHAR_SYM21AON; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EON; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'o': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'P': case 'p': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'Q': case 'q': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EON; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'R': case 'r': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DON; CHAR_SYM21EON; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'S': case 's': CHAR_SYM21AON; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EON; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'T': case 't': CHAR_SYM21AOFF; CHAR_SYM21BON; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FON; CHAR_SYM21GOFF; break;
        case 'U': case 'u': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'V': case 'v': CHAR_SYM21AON; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EON; CHAR_SYM21FOFF; CHAR_SYM21GOFF; break;
        case 'W': case 'w': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EON; CHAR_SYM21FOFF; CHAR_SYM21GON; break;
        case 'X': case 'x': CHAR_SYM21AON; CHAR_SYM21BOFF; CHAR_SYM21CON; CHAR_SYM21DOFF; CHAR_SYM21EON; CHAR_SYM21FOFF; CHAR_SYM21GON; break;
        case 'Y': case 'y': CHAR_SYM21AON; CHAR_SYM21BOFF; CHAR_SYM21CON; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FON; CHAR_SYM21GOFF; break;
        case 'Z': case 'z': CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21CON; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GON; break;
        
        default: CHAR_SYM21AOFF; CHAR_SYM21BOFF; CHAR_SYM21COFF; CHAR_SYM21DOFF; CHAR_SYM21EOFF; CHAR_SYM21FOFF; CHAR_SYM21GOFF;
    }
}

void LCD_DIG4(unsigned char chr) 
{
    switch (chr)
    {
        case 0: case '0': case 'O':DIG_SYM04AON;   DIG_SYM04BON;   DIG_SYM04CON;   DIG_SYM04DON;   DIG_SYM04EON;   DIG_SYM04FON;   DIG_SYM04GOFF;  break;
        case 1: case '1': DIG_SYM04AOFF;  DIG_SYM04BON;   DIG_SYM04CON;   DIG_SYM04DOFF;  DIG_SYM04EOFF;  DIG_SYM04FOFF;  DIG_SYM04GOFF;  break;
        case 2: case '2': DIG_SYM04AON;   DIG_SYM04BON;   DIG_SYM04COFF;  DIG_SYM04DON;   DIG_SYM04EON;   DIG_SYM04FOFF;  DIG_SYM04GON;   break;
        case 3: case '3': DIG_SYM04AON;   DIG_SYM04BON;   DIG_SYM04CON;   DIG_SYM04DON;   DIG_SYM04EOFF;  DIG_SYM04FOFF;  DIG_SYM04GON;   break;
        case 4: case '4': DIG_SYM04AOFF;  DIG_SYM04BON;   DIG_SYM04CON;   DIG_SYM04DOFF;  DIG_SYM04EOFF;  DIG_SYM04FON;   DIG_SYM04GON;   break;
        case 5: case '5': DIG_SYM04AON;   DIG_SYM04BOFF;  DIG_SYM04CON;   DIG_SYM04DON;   DIG_SYM04EOFF;  DIG_SYM04FON;   DIG_SYM04GON;   break;
        case 6: case '6': DIG_SYM04AON;   DIG_SYM04BOFF;  DIG_SYM04CON;   DIG_SYM04DON;   DIG_SYM04EON;   DIG_SYM04FON;   DIG_SYM04GON;   break;
        case 7: case '7': DIG_SYM04AON;   DIG_SYM04BON;   DIG_SYM04CON;   DIG_SYM04DOFF;  DIG_SYM04EOFF;  DIG_SYM04FOFF;  DIG_SYM04GOFF;  break;
        case 8: case '8': DIG_SYM04AON;   DIG_SYM04BON;   DIG_SYM04CON;   DIG_SYM04DON;   DIG_SYM04EON;   DIG_SYM04FON;   DIG_SYM04GON;   break;
        case 9: case '9': DIG_SYM04AON;   DIG_SYM04BON;   DIG_SYM04CON;   DIG_SYM04DON;   DIG_SYM04EOFF;  DIG_SYM04FON;   DIG_SYM04GON;   break;
        case 'A': case 'a': DIG_SYM04AON;   DIG_SYM04BON;   DIG_SYM04CON;   DIG_SYM04DOFF;   DIG_SYM04EON;   DIG_SYM04FON;   DIG_SYM04GON; break;
        case 'B': case 'b': DIG_SYM04AOFF; DIG_SYM04BOFF; DIG_SYM04CON; DIG_SYM04DON; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GON; break;
        case 'C': case 'c': DIG_SYM04AON; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DON; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GOFF; break;
        case 'D': case 'd': DIG_SYM04AOFF; DIG_SYM04BON; DIG_SYM04CON; DIG_SYM04DON; DIG_SYM04EON; DIG_SYM04FOFF; DIG_SYM04GON; break;
        case 'E': case 'e': DIG_SYM04AON; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DON; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GON; break;
        case 'F': case 'f': DIG_SYM04AON; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DOFF; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GON; break;
        case 'G': case 'g': DIG_SYM04AON; DIG_SYM04BOFF; DIG_SYM04CON; DIG_SYM04DON; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GOFF; break;
        case 'H': case 'h': DIG_SYM04AOFF; DIG_SYM04BON; DIG_SYM04CON; DIG_SYM04DOFF; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GON; break;
        case 'I': case 'i': DIG_SYM04AOFF; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DOFF; DIG_SYM04EOFF; DIG_SYM04FOFF; DIG_SYM04GOFF; break;
        case 'J': case 'j': DIG_SYM04AOFF; DIG_SYM04BON; DIG_SYM04CON; DIG_SYM04DON; DIG_SYM04EON; DIG_SYM04FOFF; DIG_SYM04GOFF; break;
        case 'K': case 'k': DIG_SYM04AOFF; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DOFF; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GON; break;
        case 'L': case 'l': DIG_SYM04AOFF; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DON; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GOFF; break;
        case 'M': case 'm': DIG_SYM04AOFF; DIG_SYM04BON; DIG_SYM04CON; DIG_SYM04DOFF; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GOFF; break;
        case 'N': case 'n': DIG_SYM04AOFF; DIG_SYM04BON; DIG_SYM04CON; DIG_SYM04DOFF; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GOFF; break;
        case 'o': DIG_SYM04AOFF; DIG_SYM04BOFF; DIG_SYM04CON; DIG_SYM04DON; DIG_SYM04EON; DIG_SYM04FOFF; DIG_SYM04GON; break;
        case 'P': case 'p': DIG_SYM04AON; DIG_SYM04BON; DIG_SYM04COFF; DIG_SYM04DOFF; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GON; break;
        case 'Q': case 'q': DIG_SYM04AON; DIG_SYM04BON; DIG_SYM04CON; DIG_SYM04DON; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GOFF; break;
        case 'R': case 'r': DIG_SYM04AON; DIG_SYM04BON; DIG_SYM04COFF; DIG_SYM04DOFF; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GON; break;
        case 'S': case 's': DIG_SYM04AON; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DON; DIG_SYM04EOFF; DIG_SYM04FOFF; DIG_SYM04GOFF; break;
        case 'T': case 't': DIG_SYM04AON; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DOFF; DIG_SYM04EOFF; DIG_SYM04FOFF; DIG_SYM04GOFF; break;
        case 'U': case 'u': DIG_SYM04AOFF; DIG_SYM04BON; DIG_SYM04CON; DIG_SYM04DON; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GOFF; break;
        case 'V': case 'v': DIG_SYM04AOFF; DIG_SYM04BON; DIG_SYM04CON; DIG_SYM04DOFF; DIG_SYM04EOFF; DIG_SYM04FOFF; DIG_SYM04GOFF; break;
        case 'W': case 'w': DIG_SYM04AOFF; DIG_SYM04BON; DIG_SYM04CON; DIG_SYM04DOFF; DIG_SYM04EON; DIG_SYM04FON; DIG_SYM04GOFF; break;
        case 'X': case 'x': DIG_SYM04AOFF; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DOFF; DIG_SYM04EOFF; DIG_SYM04FOFF; DIG_SYM04GOFF; break;
        case 'Y': case 'y': DIG_SYM04AOFF; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DOFF; DIG_SYM04EOFF; DIG_SYM04FOFF; DIG_SYM04GOFF; break;
        case 'Z': case 'z': DIG_SYM04AON; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DON; DIG_SYM04EOFF; DIG_SYM04FOFF; DIG_SYM04GOFF; break;

        default: DIG_SYM04AOFF; DIG_SYM04BOFF; DIG_SYM04COFF; DIG_SYM04DOFF; DIG_SYM04EOFF; DIG_SYM04FOFF; DIG_SYM04GOFF;
    }    
    
    switch (chr)
    {
        case 0: case '0': case 'O': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF;  break;
        case 1: case '1': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF;  break;
        case 2: case '2': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF;  break;
        case 3: case '3': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF;  break;
        case 4: case '4': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF;  break;
        case 5: case '5': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF;  break;
        case 6: case '6': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF;  break;
        case 7: case '7': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF;  break;
        case 8: case '8': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF;  break;
        case 9: case '9': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF;  break;
        case 'A': case 'a': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'B': case 'b': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'C': case 'c': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'D': case 'd': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'E': case 'e': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'F': case 'f': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'G': case 'g': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'H': case 'h': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'I': case 'i': CHAR_SYM22AOFF; CHAR_SYM22BON; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FON; CHAR_SYM22GOFF; break;
        case 'J': case 'j': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'K': case 'k': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22CON; CHAR_SYM22DOFF; CHAR_SYM22EON; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'L': case 'l': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'M': case 'm': CHAR_SYM22AON; CHAR_SYM22BOFF; CHAR_SYM22CON; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'N': case 'n': CHAR_SYM22AON; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EON; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'o': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'P': case 'p': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'Q': case 'q': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EON; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'R': case 'r': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DON; CHAR_SYM22EON; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'S': case 's': CHAR_SYM22AON; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EON; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'T': case 't': CHAR_SYM22AOFF; CHAR_SYM22BON; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FON; CHAR_SYM22GOFF; break;
        case 'U': case 'u': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'V': case 'v': CHAR_SYM22AON; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EON; CHAR_SYM22FOFF; CHAR_SYM22GOFF; break;
        case 'W': case 'w': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EON; CHAR_SYM22FOFF; CHAR_SYM22GON; break;
        case 'X': case 'x': CHAR_SYM22AON; CHAR_SYM22BOFF; CHAR_SYM22CON; CHAR_SYM22DOFF; CHAR_SYM22EON; CHAR_SYM22FOFF; CHAR_SYM22GON; break;
        case 'Y': case 'y': CHAR_SYM22AON; CHAR_SYM22BOFF; CHAR_SYM22CON; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FON; CHAR_SYM22GOFF; break;
        case 'Z': case 'z': CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22CON; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GON; break;
        
        default: CHAR_SYM22AOFF; CHAR_SYM22BOFF; CHAR_SYM22COFF; CHAR_SYM22DOFF; CHAR_SYM22EOFF; CHAR_SYM22FOFF; CHAR_SYM22GOFF;
    }  
}

void LCD_DIG5(unsigned char chr) 
{
    switch (chr)
    {
        case 0: case '0': case 'O': DIG_SYM05AON;   DIG_SYM05BON;   DIG_SYM05CON;   DIG_SYM05DON;   DIG_SYM05EON;   DIG_SYM05FON;   DIG_SYM05GOFF;  break;
        case 1: case '1': DIG_SYM05AOFF;  DIG_SYM05BON;   DIG_SYM05CON;   DIG_SYM05DOFF;  DIG_SYM05EOFF;  DIG_SYM05FOFF;  DIG_SYM05GOFF;  break;
        case 2: case '2': DIG_SYM05AON;   DIG_SYM05BON;   DIG_SYM05COFF;  DIG_SYM05DON;   DIG_SYM05EON;   DIG_SYM05FOFF;  DIG_SYM05GON;   break;
        case 3: case '3': DIG_SYM05AON;   DIG_SYM05BON;   DIG_SYM05CON;   DIG_SYM05DON;   DIG_SYM05EOFF;  DIG_SYM05FOFF;  DIG_SYM05GON;   break;
        case 4: case '4': DIG_SYM05AOFF;  DIG_SYM05BON;   DIG_SYM05CON;   DIG_SYM05DOFF;  DIG_SYM05EOFF;  DIG_SYM05FON;   DIG_SYM05GON;   break;
        case 5: case '5': DIG_SYM05AON;   DIG_SYM05BOFF;  DIG_SYM05CON;   DIG_SYM05DON;   DIG_SYM05EOFF;  DIG_SYM05FON;   DIG_SYM05GON;   break;
        case 6: case '6': DIG_SYM05AON;   DIG_SYM05BOFF;  DIG_SYM05CON;   DIG_SYM05DON;   DIG_SYM05EON;   DIG_SYM05FON;   DIG_SYM05GON;   break;
        case 7: case '7': DIG_SYM05AON;   DIG_SYM05BON;   DIG_SYM05CON;   DIG_SYM05DOFF;  DIG_SYM05EOFF;  DIG_SYM05FOFF;  DIG_SYM05GOFF;  break;
        case 8: case '8': DIG_SYM05AON;   DIG_SYM05BON;   DIG_SYM05CON;   DIG_SYM05DON;   DIG_SYM05EON;   DIG_SYM05FON;   DIG_SYM05GON;   break;
        case 9: case '9': DIG_SYM05AON;   DIG_SYM05BON;   DIG_SYM05CON;   DIG_SYM05DON;   DIG_SYM05EOFF;  DIG_SYM05FON;   DIG_SYM05GON;   break;
        case 'A': case 'a': DIG_SYM05AON;   DIG_SYM05BON;   DIG_SYM05CON;   DIG_SYM05DOFF;   DIG_SYM05EON;   DIG_SYM05FON;   DIG_SYM05GON; break;
        case 'B': case 'b': DIG_SYM05AOFF; DIG_SYM05BOFF; DIG_SYM05CON; DIG_SYM05DON; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GON; break;
        case 'C': case 'c': DIG_SYM05AON; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DON; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GOFF; break;
        case 'D': case 'd': DIG_SYM05AOFF; DIG_SYM05BON; DIG_SYM05CON; DIG_SYM05DON; DIG_SYM05EON; DIG_SYM05FOFF; DIG_SYM05GON; break;
        case 'E': case 'e': DIG_SYM05AON; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DON; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GON; break;
        case 'F': case 'f': DIG_SYM05AON; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DOFF; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GON; break;
        case 'G': case 'g': DIG_SYM05AON; DIG_SYM05BOFF; DIG_SYM05CON; DIG_SYM05DON; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GOFF; break;
        case 'H': case 'h': DIG_SYM05AOFF; DIG_SYM05BON; DIG_SYM05CON; DIG_SYM05DOFF; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GON; break;
        case 'I': case 'i': DIG_SYM05AOFF; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DOFF; DIG_SYM05EOFF; DIG_SYM05FOFF; DIG_SYM05GOFF; break;
        case 'J': case 'j': DIG_SYM05AOFF; DIG_SYM05BON; DIG_SYM05CON; DIG_SYM05DON; DIG_SYM05EON; DIG_SYM05FOFF; DIG_SYM05GOFF; break;
        case 'K': case 'k': DIG_SYM05AOFF; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DOFF; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GON; break;
        case 'L': case 'l': DIG_SYM05AOFF; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DON; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GOFF; break;
        case 'M': case 'm': DIG_SYM05AOFF; DIG_SYM05BON; DIG_SYM05CON; DIG_SYM05DOFF; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GOFF; break;
        case 'N': case 'n': DIG_SYM05AOFF; DIG_SYM05BON; DIG_SYM05CON; DIG_SYM05DOFF; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GOFF; break;
        case 'o': DIG_SYM05AOFF; DIG_SYM05BOFF; DIG_SYM05CON; DIG_SYM05DON; DIG_SYM05EON; DIG_SYM05FOFF; DIG_SYM05GON; break;
        case 'P': case 'p': DIG_SYM05AON; DIG_SYM05BON; DIG_SYM05COFF; DIG_SYM05DOFF; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GON; break;
        case 'Q': case 'q': DIG_SYM05AON; DIG_SYM05BON; DIG_SYM05CON; DIG_SYM05DON; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GOFF; break;
        case 'R': case 'r': DIG_SYM05AON; DIG_SYM05BON; DIG_SYM05COFF; DIG_SYM05DOFF; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GON; break;
        case 'S': case 's': DIG_SYM05AON; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DON; DIG_SYM05EOFF; DIG_SYM05FOFF; DIG_SYM05GOFF; break;
        case 'T': case 't': DIG_SYM05AON; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DOFF; DIG_SYM05EOFF; DIG_SYM05FOFF; DIG_SYM05GOFF; break;
        case 'U': case 'u': DIG_SYM05AOFF; DIG_SYM05BON; DIG_SYM05CON; DIG_SYM05DON; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GOFF; break;
        case 'V': case 'v': DIG_SYM05AOFF; DIG_SYM05BON; DIG_SYM05CON; DIG_SYM05DOFF; DIG_SYM05EOFF; DIG_SYM05FOFF; DIG_SYM05GOFF; break;
        case 'W': case 'w': DIG_SYM05AOFF; DIG_SYM05BON; DIG_SYM05CON; DIG_SYM05DOFF; DIG_SYM05EON; DIG_SYM05FON; DIG_SYM05GOFF; break;
        case 'X': case 'x': DIG_SYM05AOFF; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DOFF; DIG_SYM05EOFF; DIG_SYM05FOFF; DIG_SYM05GOFF; break;
        case 'Y': case 'y': DIG_SYM05AOFF; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DOFF; DIG_SYM05EOFF; DIG_SYM05FOFF; DIG_SYM05GOFF; break;
        case 'Z': case 'z': DIG_SYM05AON; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DON; DIG_SYM05EOFF; DIG_SYM05FOFF; DIG_SYM05GOFF; break;

        default: DIG_SYM05AOFF; DIG_SYM05BOFF; DIG_SYM05COFF; DIG_SYM05DOFF; DIG_SYM05EOFF; DIG_SYM05FOFF; DIG_SYM05GOFF;
    }    
    
    switch (chr)
    {
        case 0: case '0': case 'O': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF;  break;
        case 1: case '1': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF;  break;
        case 2: case '2': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF;  break;
        case 3: case '3': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF;  break;
        case 4: case '4': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF;  break;
        case 5: case '5': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF;  break;
        case 6: case '6': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF;  break;
        case 7: case '7': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF;  break;
        case 8: case '8': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF;  break;
        case 9: case '9': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF;  break;
        case 'A': case 'a': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'B': case 'b': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'C': case 'c': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'D': case 'd': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'E': case 'e': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'F': case 'f': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'G': case 'g': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'H': case 'h': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'I': case 'i': CHAR_SYM23AOFF; CHAR_SYM23BON; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FON; CHAR_SYM23GOFF; break;
        case 'J': case 'j': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'K': case 'k': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23CON; CHAR_SYM23DOFF; CHAR_SYM23EON; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'L': case 'l': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'M': case 'm': CHAR_SYM23AON; CHAR_SYM23BOFF; CHAR_SYM23CON; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'N': case 'n': CHAR_SYM23AON; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EON; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'o': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'P': case 'p': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'Q': case 'q': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EON; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'R': case 'r': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DON; CHAR_SYM23EON; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'S': case 's': CHAR_SYM23AON; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EON; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'T': case 't': CHAR_SYM23AOFF; CHAR_SYM23BON; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FON; CHAR_SYM23GOFF; break;
        case 'U': case 'u': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'V': case 'v': CHAR_SYM23AON; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EON; CHAR_SYM23FOFF; CHAR_SYM23GOFF; break;
        case 'W': case 'w': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EON; CHAR_SYM23FOFF; CHAR_SYM23GON; break;
        case 'X': case 'x': CHAR_SYM23AON; CHAR_SYM23BOFF; CHAR_SYM23CON; CHAR_SYM23DOFF; CHAR_SYM23EON; CHAR_SYM23FOFF; CHAR_SYM23GON; break;
        case 'Y': case 'y': CHAR_SYM23AON; CHAR_SYM23BOFF; CHAR_SYM23CON; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FON; CHAR_SYM23GOFF; break;
        case 'Z': case 'z': CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23CON; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GON; break;
        
        default: CHAR_SYM23AOFF; CHAR_SYM23BOFF; CHAR_SYM23COFF; CHAR_SYM23DOFF; CHAR_SYM23EOFF; CHAR_SYM23FOFF; CHAR_SYM23GOFF;
    }
}
/**
 End of File
*/